# Generated by Django 4.1.3 on 2023-01-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_userinfo_name_alter_userinfo_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo", name="age", field=models.IntegerField(default=2),
        ),
    ]
