# Generated by Django 4.1.3 on 2023-01-12 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="account",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="余额"
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="create_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="入职时间"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(default=2, verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="name",
            field=models.CharField(max_length=32, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(max_length=64, verbose_name="密码"),
        ),
    ]
